# Generated by Django 6.0.7 on 2026-07-27 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_bit_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bit_item',
            new_name='bid_item',
        ),
    ]
