# Generated by Django 6.0.7 on 2026-07-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_bit_item_bid_bid_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_endind',
            field=models.DateTimeField(),
        ),
    ]
